/*
    다대다(M:N) 관계
    1. 현실에서 빈번히 나타나지만 주의해야 하는 관계이다.
    2. 두 테이블을 다대다 관계로 직접 연결하는 것은 불가능하다.
    3. 두 테이블을 관계 맺어 줄 별도의 테이블이 추가로 필요하다.
    4. 다대다(M:N) 관계 1개는 일대다(1:M) 관계 2개로 만들 수 있다.
*/


/* 
 M:N 관계   
 1. PK를 가진 부모 학생, 과목을 먼저 생성해줘야 한다.
 2. FK가 포함되어있는 자식테이블인 수강신청 테이블을 마지막으로 생성한다.
*/


-- 테이블 삭제 

DROP TABLE ENROLL_TBL;
DROP TABLE SUBJECT_TBL;
DROP TABLE STUDENT_TBL;




--학생 테이블 생성 

CREATE TABLE STUDENT_TBL(
    STU_NO VARCHAR2(5 BYTE) NOT NULL,
    STU_NAME VARCHAR2 (15 BYTE),
    STU_AGE NUMBER(2),
    CONSTRAINT PK_STUDENT PRIMARY KEY(STU_NO)
);

--과목 테이블 생성 
CREATE TABLE SUBJECT_TBL(
    SJT_CODE VARCHAR2(1 BYTE) NOT NULL,
    SJT_NAME VARCHAR2(10 BYTE), 
    PROFESSOR VARCHAR2 (15 BYTE),
    CONSTRAINT PK_SUBJECT PRIMARY KEY(SJT_CODE)
);

--수강신청 테이블 생성 

CREATE TABLE ENROLL_TBL(
    ENR_NO NUMBER NOT NULL,
    STU_NO VARCHAR2(5 BYTE) NOT NULL,
    SJT_CODE VARCHAR2(1 BYTE) NOT NULL,
    CONSTRAINT PK_ENROLL PRIMARY KEY(ENR_NO),
    CONSTRAINT FK_ENROLL_STUDENT FOREIGN KEY(STU_NO) REFERENCES STUDENT_TBL(STU_NO) ON DELETE CASCADE, -- NOT NULL 이라 ON DELETE CASCADE만 쓸 수 있음 
    CONSTRAINT FK_ENROLL_SUBJECT FOREIGN KEY(SJT_CODE) REFERENCES SUBJECT_TBL(SJT_CODE) ON DELETE CASCADE -- NOT NULL 이라 ON DELETE CASCADE만 쓸 수 있음 
);
