
/* 
 M:N에서는 
 PK를 가진 부모 학생, 과목을 먼저 생성해줘야 하고 FK가 포함되어있는 자식테이블인 수강신청 테이블을 
 마지막으로 생성한다 
 

*/



--테이블 삭제(주의! 생성의 역순으로 삭제할 것!)
DROP TABLE ENROLL_TBL;
DROP TABLE SUBJECT_TBL;
DROP TABLE STUDENT_TBL;



--테이블 생성 
CREATE TABLE STUDENT_TBL(
STUDENT_STNO VARCHAR2(10 BYTE) NOT NULL,
STUDENT_NAME VARCHAR2(10 BYTE), 
STUDENT_AGE NUMBER(3),
CONSTRAINT PK_STUDENT_ST PRIMARY KEY(STUDENT_STNO)
);

CREATE TABLE SUBJECT_TBL(
SUBJECT_CODE VARCHAR2(5 BYTE) NOT NULL,
SUBJECT_NAME VARCHAR2(10 BYTE),
SUBJECT_PRO VARCHAR2(10 BYTE),
CONSTRAINT PK_SUBJECT_CODE PRIMARY KEY(SUBJECT_CODE)
);

CREATE TABLE ENROLL_TBL(
ENROLL_NO NUMBER(3) NOT NULL,
STUDENT_STNO VARCHAR2(10 BYTE),
ENROLL_CODE VARCHAR2(5 BYTE),
CONSTRAINT PK_ENROLL_NO PRIMARY KEY(ENROLL_NO),
CONSTRAINT FK_ENROLL_STNO FOREIGN KEY(STUDENT_STNO) REFERENCES STUDENT_TBL(STUDENT_STNO) 
);


