

/*
기본키 제약조건 
CONSTRAINT 제약조건명 PRIMARY KEY(컬럼명) 

외래키 제약조건 
CONSTRAINT PK_테이블명 PRIMARY KEY(컬럼명) 
CONSTRAINT FK_제약조건명 FOREIGN KEY(컬럼명) REFERENCES 부모테이블(참조컬럼명) 
*/

--테이블 삭제 
DROP TABLE PCD_TBL;
DROP TABLE PJT_TBL;
DROP TABLE EMP_TBL;
DROP TABLE DEPT_TBL;

--테이블 생성 

CREATE TABLE DEPT_TBL(
    DEPT_NO VARCHAR2(15 BYTE) NOT NULL,
    DEPT_NAME VARCHAR2(30 BYTE),
    DEPT_LOCATION VARCHAR2(50 BYTE),
    CONSTRAINT PK_DEPT_NO PRIMARY KEY(DEPT_NO)
);

CREATE TABLE EMP_TBL(
    EMP_NO NUMBER NOT NULL,
    DEPT_NO VARCHAR2(15 BYTE),
    POSTION CHAR(10 BYTE),
    NAME VARCHAR2(15 BYTE),
    HIRE_DATE DATE, 
    SALARY NUMBER,
    CONSTRAINT PK_EMP_NO PRIMARY KEY(EMP_NO),
    CONSTRAINT FK_DEPT_NO FOREIGN KEY(DEPT_NO) REFERENCES DEPT_TBL(DEPT_NO)
);

CREATE TABLE PJT_TBL(
    PJT_NO NUMBER NOT NULL,
    PJT_NAME VARCHAR2(30 BYTE),
    BEGIN_DATE DATE,
    END_DATE DATE,
    CONSTRAINT PK_PJT_NO PRIMARY KEY(PJT_NO)
);

CREATE TABLE PCD_TBL(
    PCD_NO NUMBER NOT NULL,
    EMP_NO NUMBER,
    PJT_NO NUMBER,
    PJT_STATE NUMBER NOT NULL,
    CONSTRAINT PK_PCD_NO PRIMARY KEY(PCD_NO),
    CONSTRAINT FK_EMP_NO FOREIGN KEY(EMP_NO) REFERENCES EMP_TBL(EMP_NO),
    CONSTRAINT FK_PJT_NO FOREIGN KEY(PJT_NO) REFERENCES PJT_TBL(PJT_NO)
  );  
    
    
    
