

/*
기본키 제약조건 
CONSTRAINT 제약조건명 PRIMARY KEY(컬럼명) 

외래키 제약조건 
CONSTRAINT PK_테이블명 PRIMARY KEY(컬럼명) 
CONSTRAINT FK_제약조건명 FOREIGN KEY(컬럼명) REFERENCES 부모테이블(참조컬럼명) 
*/

--테이블 삭제 

DROP TABLE PROCEEDING_TBL;
DROP TABLE PROJECT_TBL;
DROP TABLE EMPLOYEE_TBL;
DROP TABLE DEPARTMENT_TBL;


--테이블 생성 
CREATE TABLE DEPARTMENT_TBL(
    DEPT_NO VARCHAR2(15 BYTE) NOT NULL,
    DEPT_NAME VARCHAR2(30 BYTE),
    DEPT_LOCATION VARCHAR2 (50 BYTE),
    CONSTRAINT PK_DEPT PRIMARY KEY(DEPT_NO)
);

CREATE TABLE EMPLOYEE_TBL(
    EMP_NO NUMBER NOT NULL,
    DEPT_NO VARCHAR2 (15 BYTE),
    POSTION CHAR(10 BYTE),
    NAME VARCHAR2 (15 BYTE),
    HIRE_DATE DATE,
    SALARY NUMBER,
    CONSTRAINT PK_EMP PRIMARY KEY(EMP_NO),
    CONSTRAINT FK_EMP_DEPT FOREIGN KEY(DEPT_NO) REFERENCES DEPARTMENT_TBL(DEPT_NO) ON DELETE SET NULL --부서가 없어지면 사원의 부서정보만 NULL 처리 된다. 새로운 부서가 생기면 새로운 부서값 넣어주면 되니까. 
);

CREATE TABLE PROJECT_TBL (
    PJT_NO NUMBER NOT NULL,
    PJT_NAME VARCHAR2(30 BYTE),
    BEGIN_DATE DATE, 
    END_DATE DATE,
    CONSTRAINT PJT PRIMARY KEY(PJT_NO)
);


CREATE TABLE PROCEEDING_TBL (
    PCD_NO NUMBER NOT NULL,
    EMP_NO NUMBER NULL,
    PJT_NO NUMBER NULL,
    PJT_STATE NUMBER NOT NULL,
    CONSTRAINT PROCEEDING PRIMARY KEY(PCD_NO),
    CONSTRAINT PROCEEDING_EMP FOREIGN KEY(EMP_NO) REFERENCES EMPLOTEE_TBL(EMP_NO) ON DELETE SET NULL,
    CONSTRAINT PROCEEDING_PJT FOREIGN KEY(PJT_NO) REFERENCES PROJECT_TBL(PJT_NO) ON DELETE SET NULL
);
